version: "3.1"
services:
    image: 
        build: .
        container_name: dagpi-image
        env_file: .env
        restart: always
        expose: 
            - 5000
        ports: 
            - 5000:5000
        